### ISSUE TITLE
Creative Cropping with the piano sample

### ISSUE THREAD

**Issue by jayesrule** [akseong/sonifyr#1]
Just had a thought about incorporating samples. Since the piano sample is so long, can we find a way to create a function where we specify our desired length and pitch, the function will then stretch the piano sample appropriately and then crop it afterwards?

**Comment by akseong** [comment]
Seems like the hardest part would be identifying the original sample's pitch?  I would think other things would fall into place after that.  @sebwaz?

**Comment by akseong** [comment]
After looking at this more, I think it makes more sense to preserve the whole sample --- the user can just crop the sample the way they want it.   But to do what you're saying while otherwise preserving the sample, we would need 4 functions: 
1. id_pitch() to identify current sample's pitch
2. id_shift() to calculate magnitude of shift to desired pitch
3. repitch() to re-pitch without time-stretch
4. t_stretch() to time-stretch without re-pitch

I think these would all be necessary things anyways if we want to allow users to use their own sounds.  

---
2 seems easy.  [Wikipedia identifies some algorithms](https://en.wikipedia.org/wiki/Audio_time_stretching_and_pitch_scaling) to do 1, 3, and 4.  

Then a user could load an audio sample `y`, crop it however they want, and then apply the functions in order:
`
pitch <- id_pitch(y)
shift <- id_shift(pitch, desired_pitch)
repitched <- repitch(y, shift)
y_new <- t_stretch(repitched, desired_t)
`

**Comment by akseong** [comment]
last thought for now: say I use a sample that has multiple pitches.  How does id_pitch() decide what the audio sample's pitch is?

**Comment by sebwaz** [comment]
Seems we've largely addressed these issues at this point
